name: Automated Lighthouse Report

on:
  workflow_run:
    workflows: ["Deploy Next.js site to Pages"] # 🔁 Replace with the name of the triggering workflow
    types:
      - completed

jobs:
  build-and-archive:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install dependencies
        run: npm install

      - name: Run main script
        run: node scripts/main.mjs

      - name: Archive project files
        uses: actions/upload-artifact@v4
        with:
          name: project-archive
          path: auto_*
          if-no-files-found: warn
